diary/urls.py
from django.urls import path

from . import views


app_name = 'diary'
urlpatterns = [
    path('', views.IndexView.as_view(), name="index"),
    path('inquiry/', views.InquiryView.as_view(), name="inquiry"),
    path('diary-list/', views.DiaryListView.as_view(), name="diary_list"),
    path('diary-detail/<int:pk>/', views.DiaryDetailView.as_view(), name="diary_detail"),
    path('diary-create/', views.DiaryCreateView.as_view(), name="diary_create"),
    path('diary-update/<int:pk>/', views.DiaryUpdateView.as_view(), name="diary_update"),
    path('diary-delete/<int:pk>/', views.DiaryDeleteView.as_view(), name="diary_delete"),
    path('good/', views.good, name='good'),
    path('diary_list/plot/<int:pk>/', views.get_svg, name='plot'),
    path('diary_list/twitter/<int:pk>/', views.twitter, name='twitter'),
    path('twitter_connect/', views.TwitterConnectView.as_view(), name="twitter_connect"),
    path('twitter_change/<int:pk>/', views.TwitterChangeView.as_view(), name="twitter_change"),
]

private_diary/urls.py
from django.contrib import admin
from django.contrib.staticfiles.urls import static
from django.urls import path, include

from . import settings_common, settings_dev

urlpatterns = [
    # path('admin/', admin.site.urls),  # 管理サイトの旧URLはコメントアウト
    path('control/', admin.site.urls),  # 管理サイトの新URLを登録
    path('', include('diary.urls')),
    path('accounts/', include('allauth.urls')),
]

# 開発サーバーでメディアを配信できるようにする設定
urlpatterns += static(settings_common.MEDIA_URL, document_root=settings_dev.MEDIA_ROOT)

diary/models.py
from accounts.models import CustomUser
from django.db import models


class Diary(models.Model):

    user = models.ForeignKey(CustomUser, verbose_name='ユーザー', on_delete=models.PROTECT)
    date = models.DateField(verbose_name='日付(例：2020-01-01)', blank=True, null=True)
    distance = models.FloatField(verbose_name='距離(km)', blank=True, null=True)
    twitter_name = models.CharField(verbose_name='Twitterアカウント名', max_length=50, blank=True, null=True)
    photo1 = models.ImageField(verbose_name='写真1', blank=True, null=True)
    created_at = models.DateTimeField(verbose_name='作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='更新日時', auto_now=True)


    class Meta:
        verbose_name_plural = 'Diary'

    def __str__(self):
        return str(self.date)


class Good(models.Model):
    good = models.IntegerField(verbose_name='いいね', blank=True, null=True)
    class Meta:
        verbose_name_plural = 'Good'

diary/forms.py
from django import forms
from django.core.mail import EmailMessage

from .models import Diary


class InquiryForm(forms.Form):
    name = forms.CharField(label='お名前', max_length=30)
    email = forms.EmailField(label='メールアドレス')
    title = forms.CharField(label='タイトル', max_length=30)
    message = forms.CharField(label='メッセージ', widget=forms.Textarea)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        self.fields['name'].widget.attrs['class'] = 'form-control col-9'
        self.fields['name'].widget.attrs['placeholder'] = 'お名前をここに入力してください。'

        self.fields['email'].widget.attrs['class'] = 'form-control col-11'
        self.fields['email'].widget.attrs['placeholder'] = 'メールアドレスをここに入力してください。'

        self.fields['title'].widget.attrs['class'] = 'form-control col-11'
        self.fields['title'].widget.attrs['placeholder'] = 'タイトルをここに入力してください。'

        self.fields['message'].widget.attrs['class'] = 'form-control col-12'
        self.fields['message'].widget.attrs['placeholder'] = 'メッセージをここに入力してください。'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        title = self.cleaned_data['title']
        message = self.cleaned_data['message']

        subject = 'お問い合わせ {}'.format(title)
        message = '送信者名: {0}\nメールアドレス: {1}\nメッセージ:\n{2}'.format(name, email, message)
        from_email = 'ebikazuki.works@yahoo.ne.jp'
        to_list = [
            'cas.ashedar.bcaph@gmail.com'
        ]
        cc_list = [
            email
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list, cc=cc_list)
        message.send()

class DiaryCreateForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('date', 'distance',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

class TwitterForm(forms.ModelForm):
    class Meta:
        model = Diary
        fields = ('twitter_name',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

diary/views.py
import logging
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy
from django.views import generic
from django.shortcuts import redirect
from .forms import InquiryForm, DiaryCreateForm, TwitterForm
from .models import Diary
from .models import Good
from django.db.models import Sum
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import io
import os
from django.http import HttpResponse
import datetime
import matplotlib.dates as mdates
import twitter

#twitter-pythonのAPI認証
t = twitter.Api(consumer_key = os.environ.get('CONSUMER_KEY'),
                  consumer_secret = os.environ.get('CONSUMER_SECRET'),
                  access_token_key = os.environ.get('ACCESS_TOKEN_KEY'),
                  access_token_secret = os.environ.get('ACCESS_TOKEN_SECRET')
                  )

logger = logging.getLogger(__name__)


class IndexView(generic.TemplateView):
    template_name = "index.html"

class InquiryView(generic.FormView):
    template_name = "inquiry.html"
    form_class = InquiryForm
    success_url = reverse_lazy('diary:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        return super().form_valid(form)

class DiaryListView(LoginRequiredMixin, generic.ListView):
    model = Diary
    template_name = 'diary_list.html'
    paginate_by = 7

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        sum = Diary.objects.filter(user=self.request.user).aggregate(Sum('distance'))
        context['Sum'] = sum['distance__sum']
        frag = Diary.objects.filter(user=self.request.user).first()
        if sum['distance__sum'] != None:
            point = float(sum['distance__sum']//50)
            delta = 50-sum['distance__sum']%50
            #ユーザー名picのIDを入れている。開発環境:6,本番:10
            img_ob = Diary.objects.filter(user = 10,distance = point).first()
            context['Img_url'] = img_ob.photo1.url
            context['Delta'] = delta
        if frag != None:
            diary_ob = Diary.objects.filter(user=self.request.user).order_by('-date').first()
            context['User_pk'] = diary_ob.pk
        return context

    def get_queryset(self):
        diaries = Diary.objects.filter(user=self.request.user).order_by('-date')
        return diaries

class DiaryDetailView(LoginRequiredMixin, generic.DetailView):
    model = Diary
    template_name = 'diary_detail.html'

class DiaryCreateView(LoginRequiredMixin, generic.CreateView):
    model = Diary
    template_name = 'diary_create.html'
    form_class = DiaryCreateForm
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.user = self.request.user
        diary.save()
        messages.success(self.request, '記録を作成しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "記録の作成に失敗しました。")
        return super().form_invalid(form)

class DiaryUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Diary
    template_name = 'diary_update.html'
    form_class = DiaryCreateForm

    def get_success_url(self):
        return reverse_lazy('diary:diary_detail', kwargs={'pk': self.kwargs['pk']})

    def form_valid(self, form):
        messages.success(self.request, '記録を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "記録の更新に失敗しました。")
        return super().form_invalid(form)

class DiaryDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Diary
    template_name = 'diary_delete.html'
    success_url = reverse_lazy('diary:diary_list')

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, "記録を削除しました。")
        return super().delete(request, *args, **kwargs)


#Goodボタンの動作
def good(request):

    post = Good.objects.get(id=1)
    if request.method == 'POST':
        # データの新規追加
        if isinstance(post.good,int):
            post.good += 1
        else:
            post.good = 1

        post.save()

    return redirect('diary:diary_list')

#グラフの描画
def setPlt(pk):
    count = 0
    x=[]
    y=[]
    diaries = Diary.objects.get(id=pk)
    user = diaries.user
    diary_ob = Diary.objects.filter(user=user).order_by('-date')
    for ob in diary_ob:
        if ob.date != None:
            count += 1
            x.append(ob.date)
            y.append(ob.distance)
            if count == 7:
                break
    plt.bar(x, y, color='#00d5ff')
    plt.title(r"$\bf{One Week Trend}$", color='#3407ba')
    plt.xlabel('date')
    plt.ylabel("km")
    plt.xlim(x[0]-datetime.timedelta(days=6.5), x[0]+datetime.timedelta(days=1))
    plt.gca().xaxis.set_major_formatter(mdates.DateFormatter("%m-%d"))

# svgへの変換
def pltToSvg():
    buf = io.BytesIO()
    plt.savefig(buf, format='svg', bbox_inches='tight')
    s = buf.getvalue()
    buf.close()
    return s

#グラフ描画のメイン動作
def get_svg(request,pk):
    setPlt(pk)
    svg = pltToSvg()
    plt.cla()
    response = HttpResponse(svg, content_type='image/svg+xml')
    return response

# Tweetから「km」の前の数値を取得する関数
def run_dist(string):
    result = 0
    count = string.count("km")
    while count > 0:
        k = string.find("km")
        for i in range(1, 10):
            frag = str.isdecimal(string[k - i])
            if not frag:
                break
        result += int(string[k + 1 - i:k])
        count -= 1
        string = string[k + 1:]

    return result

# twitterの時間を変換する関数
def date_conv(str):
    # strはSun Aug 02 13:13:05 +0000 2020という形式
    year, month, date = str[26:30], str[4:7], str[8:10]
    tdatetime = datetime.datetime.strptime(year + month + date, '%Y%b%d')
    # 日本時間へ変換
    tdatetime_jp = tdatetime + datetime.timedelta(hours=9)
    tdate_jp = datetime.date(tdatetime_jp.year, tdatetime_jp.month, tdatetime_jp.day)

    return tdate_jp

# 過去一週間のランニングデータをTwitterから集める関数
def data_gather(name):
    end = datetime.date.today() + datetime.timedelta(days=1)
    start = end - datetime.timedelta(days=8)
    tweet = t.GetSearch(term='#runrun from:' + name + ' since:' + str(start) + ' until:' + str(end) + '_JST')
    date_list = []
    distance_list = []

    for s in tweet:
        date = date_conv(s.created_at)
        date_list.append(date)
        distance = run_dist(s.text)
        distance_list.append(distance)

    return date_list, distance_list

#Twitterボタンの動作
def twitter(request,pk):

    diaries = Diary.objects.get(id=pk)
    user = diaries.user
    twitter_name_ob = Diary.objects.filter(user=user).order_by("twitter_name").first()
    twitter_id = twitter_name_ob.twitter_name
    if twitter_id != None:
        date_list,distance_list = data_gather(twitter_id)
        y = 0
        for x in date_list:
            if Diary.objects.filter(user=user,date=x).first()==None:
                record = Diary(user=user, date=x, distance=distance_list[y])
                record.save()
            else:
                '''
                record_id = Diary.objects.filter(user=user, date=x).first().id
                record = Diary.objects.get(id=record_id)
                record.distance += distance_list[y]
                record.save()
                '''
            y += 1
    return redirect('diary:diary_list')

class TwitterConnectView(LoginRequiredMixin, generic.CreateView):
    model = Diary
    template_name = 'twitter_connect.html'
    form_class = TwitterForm
    success_url = reverse_lazy('diary:diary_list')

    def form_valid(self, form):
        diary = form.save(commit=False)
        diary.user = self.request.user
        diary.save()
        messages.success(self.request, 'Twitter名を登録しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Twitter名の登録に失敗しました。")
        return super().form_invalid(form)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        twitter_name_ob = Diary.objects.filter(user=self.request.user).order_by("twitter_name").first()
        if twitter_name_ob != None:
            twitter_id = twitter_name_ob.twitter_name
            context['Twitter_name'] = twitter_id
            context['pk'] = twitter_name_ob.pk
        else:
            context['Twitter_name'] = None
        return context

class TwitterChangeView(LoginRequiredMixin, generic.UpdateView):
    model = Diary
    template_name = 'twitter_change.html'
    form_class = TwitterForm
    success_url = reverse_lazy('diary:diary_list')

    '''
    def get_success_url(self):
        return reverse_lazy('diary:diary_detail', kwargs={'pk': self.kwargs['pk']})
    '''


    def form_valid(self, form):
        messages.success(self.request, 'Twitter名を更新しました。')
        return super().form_valid(form)

    def form_invalid(self, form):
        messages.error(self.request, "Twitter名を更新に失敗しました。")
        return super().form_invalid(form)

diary/templates/base.html
{% load static %}

<html lang="ja">

  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>{% block title %}{% endblock %}</title>

    <!-- Bootstrap core CSS -->
    <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom fonts for this template -->
    <link href="https://fonts.googleapis.com/css?family=Catamaran:100,200,300,400,500,600,700,800,900" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Lato:100,100i,300,300i,400,400i,700,700i,900,900i" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'css/one-page-wonder.min.css' %}" rel="stylesheet">

    <!-- My style -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
    {% block head %}{% endblock %}
  </head>

  <body>
	<div id="wrapper">
        <!-- Navigation -->
        <nav class="navbar navbar-expand-lg navbar-dark navbar-custom fixed-top">
          <div class="container">
            <a class="navbar-brand" href="{% url 'diary:index' %}">RUNRUN</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
              <ul class="navbar-nav mr-auto">
                <li class="nav-item {% block active_inquiry %}{% endblock %}">
                  <a class="nav-link" href="{% url 'diary:inquiry' %}">お問い合わせ</a>
                </li>
                {% if user.is_authenticated %}
                  <li class="nav-item {% block active_diary_list %}{% endblock %}">
                      <a class="nav-link" href="{% url 'diary:diary_list' %}">マイページ</a>
                  </li>
                   <li class="nav-item {% block active_twitter_connect %}{% endblock %}">
                      <a class="nav-link" href="{% url 'diary:twitter_connect' %}">Twitter連携</a>
                  </li>
                {% endif %}
              </ul>
              <ul class="navbar-nav ml-auto">
                {% if user.is_authenticated %}
                  <li class="nav-item">
                      <a class="nav-link" href="{% url 'account_logout' %}">Log Out</a>
                  </li>
                {% else %}
                  <li class="nav-item {% block active_signup %}{% endblock %}">
                      <a class="nav-link" href="{% url 'account_signup' %}">Sign Up</a>
                  </li>
                  <li class="nav-item {% block active_login %}{% endblock %}">
                      <a class="nav-link" href="{% url 'account_login' %}">Log In</a>
                  </li>
                {% endif %}
              </ul>
            </div>
          </div>
        </nav>

        {% block header%}{% endblock %}

        {% if messages %}
          <div class="container">
              <div class="row">
                  <div class="my-div-style w-100">
                      <ul class="messages" style="list-style: none;">
                          {% for message in messages %}
                          <li {% if message.tags %} class="{{ message.tags }}" {% endif %}>
                              {{ message }}
                          </li>
                          {% endfor %}
                      </ul>
                  </div>
              </div>
          </div>
        {% endif %}

        {% block contents%}{% endblock %}

        <!-- Footer -->
        <footer class="py-5 bg-black">
          <div class="container">
            <p class="m-0 text-center text-white small">Copyright &copy; RUNRUN 2020</p>
          </div>
          <!-- /.container -->
        </footer>

        <!-- Bootstrap core JavaScript -->
        <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
        <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>
  	</div>
  </body>

</html>

diary/templates/diary_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}記録作成 | RUNRUN{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">作成</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary_delete.html
{% extends 'base.html' %}
{% load static %}

{% block title %}記録削除 | RUNRUN{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST">
                {% csrf_token %}
                <p>本当に削除しますか？</p>
                <button class="btn btn-primary mt-5" type="submit">削除</button>
                <a class="btn btn-secondary mt-5 ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}記録詳細 | RUNRUN{% endblock %}

{% block active_diary_list %}active{% endblock %}


{% block contents %}
<div class="container">
    <div class="my-div-style w-100">
        <div class="row">
            <div class="col-3">
                <strong>日付</strong>
            </div>
            <div class="col-9">
                {{ object.date }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>本文</strong>
            </div>
            <div class="col-9">
                {{ object.distance}}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>作成日時</strong>
            </div>
            <div class="col-9">
                {{ object.created_at }}
            </div>
        </div>

        <hr>

        <div class="row">
            <div class="col-3">
                <strong>更新日時</strong>
            </div>
            <div class="col-9">
                {{ object.updated_at }}
            </div>
        </div>

        <a class="btn btn-success mt-5 mb-3" href="{% url 'diary:diary_update' object.pk %}">編集</a>
        <a class="btn btn-danger mt-5 ml-2 mb-3" href="{% url 'diary:diary_delete' object.pk %}">削除</a>
    </div>
</div>
{% endblock %}

diary/templates/diary_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}マイページ | RUNRUN{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block head %}
<link href="{% static 'css/clean-blog.min.css' %}" rel="stylesheet">
{% endblock %}

{% block contents %}
<div class="container">

    <div class="row">
        <div class="my-div-style w-100">
            <div class="col-lg-8 col-md-10 mx-auto">
                <div class="clearfix">
                    {% if Sum == None %}
                    <p>記録がありません。</p>
                    {% else %}
                    <p>あなたの合計距離：<strong>{{Sum}}km</strong></p>
                    <hr>

                    <img src="{{ Img_url }}" width=100%/>
                    <p style="text-align: right"><font size="2">あと<strong>{{Delta}}km</strong>で次の写真に変わります</font></p>
                    <hr>

                    <img src="{% url 'diary:plot' User_pk %}" width=100%><br>
                    <hr>
                    {% endif %}
                    {% if User_pk == None %}
                    <p>手入力もしくはメニューからTwitter連携をしてデータを記録してください。</p>
                    {% else %}
                    <a class="btn btn-primary float-right" href="{% url 'diary:twitter' User_pk %}">Twitter</a>
                    {% endif %}
                    <br>
                    <br>
                    <a class="btn btn-primary float-right" href="{% url 'diary:diary_create' %}">手入力</a>

                </div>
<!-- いいねボタン
                        <form action="{% url 'diary:good' %}" method="post">
                            {% csrf_token %}
                            <input type="submit" name="good" value="いいね"　id="good">{{ Good }} good!
                        </form>
-->
                {% for diary in object_list %}
                    <div class="post-preview">
                        <a href="{% url 'diary:diary_detail' diary.pk %}">
                          <p class="post-title">
                            {% if diary.date != None %}
                              {{ diary.date }}: {{ diary.distance }}km
                          </p>
                        </a>
                        <p class="post-meta">{{ diary.created_at }}</p>
                        {% endif %}
                    </div>
                    <hr>

                {% empty %}
                    <!-- <p>記録がありません。</p> -->

                {% endfor %}

                <!-- ページネーション処理 -->
                {% if is_paginated %}
                    <ul class="pagination">
                        <!-- 前ページへのリンク -->
                        {% if page_obj.has_previous %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.previous_page_number }}">
                                    <span aria-hidden="true">&laquo;</span>
                                </a>
                            </li>
                        {% endif %}

                        <!-- ページ数表示 -->
                        {% for page_num in page_obj.paginator.page_range %}
                            {% if page_obj.number == page_num %}
                                <li class="page-item active"><a class="page-link" href="#">{{ page_num }}</a></li>
                            {% else %}
                                <li class="page-item"><a class="page-link" href="?page={{ page_num }}">{{ page_num }}</a></li>
                            {% endif %}
                        {% endfor %}

                        <!-- 次ページへのリンク -->
                        {% if page_obj.has_next %}
                            <li class="page-item">
                                <a class="page-link" href="?page={{ page_obj.next_page_number }}">
                                    <span aria-hidden="true">&raquo;</span>
                                </a>
                            </li>
                        {% endif %}
                    </ul>
                {% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/diary_update.html
{% extends 'base.html' %}
{% load static %}

{% block title %}記録編集 | RUNRUN{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary" type="submit">更新</button>
                <a class="btn btn-secondary ml-2" href="{% url 'diary:diary_detail' object.pk %}">キャンセル</a>
            </form>
        </div>
    </div>
</div>
{% endblock %}

diary/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}ランニング距離を記録するサービス | RUNRUN{% endblock %}

{% block header%}
<header class="masthead text-center text-white">
  <div class="masthead-content">
    <div class="container">
      <h1 class="masthead-heading mb-0">RUNRUN</h1>
      <h2 class="masthead-subheading mb-0">今日は何km走った？</h2>
      <a href="{% url 'account_login' %}" class="btn btn-primary btn-xl rounded-pill mt-5">LOG IN</a>
    </div>
  </div>
  <div class="bg-circle-1 bg-circle"></div>
  <div class="bg-circle-2 bg-circle"></div>
  <div class="bg-circle-3 bg-circle"></div>
  <div class="bg-circle-4 bg-circle"></div>
</header>
{% endblock %}

{% block contents %}
<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'img/01.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Twitter Base</h2>
          <p>「#runrun ●●km」で走行距離を記録</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'img/02.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6">
        <div class="p-5">
          <h2 class="display-4">Visualize</h2>
          <p>走行距離を可視化</p>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <div class="row align-items-center">
      <div class="col-lg-6 order-lg-2">
        <div class="p-5">
          <img class="img-fluid rounded-circle" src="{% static 'img/03.jpg' %}" alt="">
        </div>
      </div>
      <div class="col-lg-6 order-lg-1">
        <div class="p-5">
          <h2 class="display-4">Free Service</h2>
          <p>無料のウェブサービス</p>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock %}

diary/templates/twitter_connect.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Twitter連携 | RUNRUN{% endblock %}

{% block active_diary_list %}active{% endblock %}

{% block contents %}
<div class="container">
    {% if Twitter_name == None %}
    <div class="row">
        <div class="my-div-style w-100">
            <form method="POST" enctype='multipart/form-data'>
                {% csrf_token %}
                <table class="table">
                    {{ form.as_table }}
                </table>
                <button class="btn btn-primary float-right" type="submit">連携</button>
            </form>
        </div>
    </div>
    {% else %}
    <br><br><br><br>
    <p>登録しているTwitterアカウント：<strong>{{ Twitter_name }}</strong></p>
    <a class="btn btn-primary" href="{% url 'diary:twitter_change' pk %}">変更</a>
    {% endif %}
    <hr>
    <br>
    <br>
    <h2>使い方</h2>
    <p><strong>1.#runrunで走行距離をつぶやく</strong></p>
    <br>
    <img class="img-fluid" src="{% static 'img/04.jpg' %}" alt="",width=50%>
    <br>
    <br>
    <br>
    <p><strong>2.マイページの『TWITTER』ボタンで過去7日間の記録を集計</strong></p>
    <br>
    <img class="img-fluid" src="{% static 'img/05.jpg' %}" alt="",width=50%>
    <br>
    <br>



</div>
{% endblock %}